
package com.com.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CreditScoreRequestInterface", targetNamespace = "http://ws.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface CreditScoreRequestInterface {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "CreditScoreRequest")
    @WebResult(partName = "return")
    @Action(input = "http://ws.com/CreditScoreRequestInterface/CreditScoreRequestRequest", output = "http://ws.com/CreditScoreRequestInterface/CreditScoreRequestResponse")
    public String creditScoreRequest(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

}
