
package com.com.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "LoanRequestImplementationService", targetNamespace = "http://ws.com/", wsdlLocation = "http://localhost:9999/ws/LoanRequest?wsdl")
public class LoanRequestImplementationService
    extends Service
{

    private final static URL LOANREQUESTIMPLEMENTATIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException LOANREQUESTIMPLEMENTATIONSERVICE_EXCEPTION;
    private final static QName LOANREQUESTIMPLEMENTATIONSERVICE_QNAME = new QName("http://ws.com/", "LoanRequestImplementationService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9999/ws/LoanRequest?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LOANREQUESTIMPLEMENTATIONSERVICE_WSDL_LOCATION = url;
        LOANREQUESTIMPLEMENTATIONSERVICE_EXCEPTION = e;
    }

    public LoanRequestImplementationService() {
        super(__getWsdlLocation(), LOANREQUESTIMPLEMENTATIONSERVICE_QNAME);
    }

    public LoanRequestImplementationService(WebServiceFeature... features) {
        super(__getWsdlLocation(), LOANREQUESTIMPLEMENTATIONSERVICE_QNAME, features);
    }

    public LoanRequestImplementationService(URL wsdlLocation) {
        super(wsdlLocation, LOANREQUESTIMPLEMENTATIONSERVICE_QNAME);
    }

    public LoanRequestImplementationService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LOANREQUESTIMPLEMENTATIONSERVICE_QNAME, features);
    }

    public LoanRequestImplementationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LoanRequestImplementationService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns LoanRequestInterface
     */
    @WebEndpoint(name = "LoanRequestImplementationPort")
    public LoanRequestInterface getLoanRequestImplementationPort() {
        return super.getPort(new QName("http://ws.com/", "LoanRequestImplementationPort"), LoanRequestInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LoanRequestInterface
     */
    @WebEndpoint(name = "LoanRequestImplementationPort")
    public LoanRequestInterface getLoanRequestImplementationPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.com/", "LoanRequestImplementationPort"), LoanRequestInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LOANREQUESTIMPLEMENTATIONSERVICE_EXCEPTION!= null) {
            throw LOANREQUESTIMPLEMENTATIONSERVICE_EXCEPTION;
        }
        return LOANREQUESTIMPLEMENTATIONSERVICE_WSDL_LOCATION;
    }

}
